#!/usr/bin/env python3
"""Generate deterministic UTF-8 interface packs from the reviewed English pack."""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
base = json.loads((root / "languages" / "en.json").read_text(encoding="utf-8"))

# The most visible application commands are native in every pack. Less common
# diagnostic/help strings deliberately inherit the English fallback instead of
# showing a mixture of Serbian and the selected language.
keys = [
 "Pomoć","Datoteka","Brzi početak","Prečice na tastaturi (F1)","Korisničko uputstvo (PDF)",
 "Korisničko uputstvo (tekst)","Šta je novo","Podrži razvoj…","O programu","Jezik programa",
 "Jezik:","Model:","Izaberi…","Dodatni modeli…","Otkaži","UREDI TITLOVE","Spremno.",
 "Titl","Govor","Tekst","Pusti titl","Pusti govor","Pusti novu poziciju","Pusti","Pauza",
 "Idi na:","Idi na vreme","Kopiraj trenutno vreme","Prati reprodukciju","Početak:","Kraj:",
 "Tolerancija:","Stroga","Standardna","Opuštena","Prilagođena","PRIMENI (Ctrl+Enter)",
 "PRELOMI REDOVE","PODELI","PAMETNO PODELI","SPOJI SA SLEDEĆIM","OBRIŠI RED","Preuzmi",
 "Ukloni","Nije instaliran","Automatsko prepoznavanje","NIJE PRONAĐEN","POUZDANO","PROVERITI","SLABO"
]

packs = {
"de": ["Hilfe","Datei","Schnellstart","Tastenkürzel (F1)","Benutzerhandbuch (PDF)","Benutzerhandbuch (Text)","Neuigkeiten","Entwicklung unterstützen…","Über","Programmsprache","Sprache:","Modell:","Auswählen…","Zusätzliche Modelle…","Abbrechen","UNTERTITEL BEARBEITEN","Bereit.","Untertitel","Sprache","Text","Untertitel abspielen","Sprache abspielen","Neue Position abspielen","Abspielen","Pause","Gehe zu:","Zur Zeit gehen","Aktuelle Zeit kopieren","Wiedergabe folgen","Start:","Ende:","Toleranz:","Streng","Standard","Locker","Benutzerdefiniert","ANWENDEN (Strg+Enter)","ZEILEN UMBRECHEN","TEILEN","INTELLIGENT TEILEN","MIT NÄCHSTEM VERBINDEN","ZEILE LÖSCHEN","Herunterladen","Entfernen","Nicht installiert","Automatische Erkennung","NICHT GEFUNDEN","ZUVERLÄSSIG","PRÜFEN","SCHWACH"],
"fr": ["Aide","Fichier","Démarrage rapide","Raccourcis clavier (F1)","Guide utilisateur (PDF)","Guide utilisateur (texte)","Nouveautés","Soutenir le développement…","À propos","Langue du programme","Langue :","Modèle :","Parcourir…","Modèles supplémentaires…","Annuler","MODIFIER LES SOUS-TITRES","Prêt.","Sous-titre","Parole","Texte","Lire le sous-titre","Lire la parole","Lire la nouvelle position","Lire","Pause","Aller à :","Aller au temps","Copier le temps actuel","Suivre la lecture","Début :","Fin :","Tolérance :","Stricte","Standard","Souple","Personnalisée","APPLIQUER (Ctrl+Entrée)","COUPER LES LIGNES","DIVISER","DIVISION INTELLIGENTE","FUSIONNER AVEC LE SUIVANT","SUPPRIMER LA LIGNE","Télécharger","Supprimer","Non installé","Détection automatique","NON TROUVÉ","FIABLE","À VÉRIFIER","FAIBLE"],
"es": ["Ayuda","Archivo","Inicio rápido","Atajos de teclado (F1)","Guía del usuario (PDF)","Guía del usuario (texto)","Novedades","Apoyar el desarrollo…","Acerca de","Idioma del programa","Idioma:","Modelo:","Elegir…","Modelos adicionales…","Cancelar","EDITAR SUBTÍTULOS","Listo.","Subtítulo","Voz","Texto","Reproducir subtítulo","Reproducir voz","Reproducir nueva posición","Reproducir","Pausa","Ir a:","Ir al tiempo","Copiar tiempo actual","Seguir reproducción","Inicio:","Fin:","Tolerancia:","Estricta","Estándar","Flexible","Personalizada","APLICAR (Ctrl+Enter)","AJUSTAR LÍNEAS","DIVIDIR","DIVISIÓN INTELIGENTE","UNIR CON EL SIGUIENTE","ELIMINAR FILA","Descargar","Eliminar","No instalado","Detección automática","NO ENCONTRADO","FIABLE","REVISAR","DÉBIL"],
"it": ["Aiuto","File","Avvio rapido","Scorciatoie da tastiera (F1)","Guida utente (PDF)","Guida utente (testo)","Novità","Sostieni lo sviluppo…","Informazioni","Lingua del programma","Lingua:","Modello:","Sfoglia…","Modelli aggiuntivi…","Annulla","MODIFICA SOTTOTITOLI","Pronto.","Sottotitolo","Voce","Testo","Riproduci sottotitolo","Riproduci voce","Riproduci nuova posizione","Riproduci","Pausa","Vai a:","Vai al tempo","Copia tempo corrente","Segui riproduzione","Inizio:","Fine:","Tolleranza:","Rigida","Standard","Rilassata","Personalizzata","APPLICA (Ctrl+Invio)","SPEZZA RIGHE","DIVIDI","DIVISIONE INTELLIGENTE","UNISCI AL SUCCESSIVO","ELIMINA RIGA","Scarica","Rimuovi","Non installato","Rilevamento automatico","NON TROVATO","AFFIDABILE","DA VERIFICARE","DEBOLE"],
"pt": ["Ajuda","Ficheiro","Início rápido","Atalhos de teclado (F1)","Manual do utilizador (PDF)","Manual do utilizador (texto)","Novidades","Apoiar o desenvolvimento…","Sobre","Idioma do programa","Idioma:","Modelo:","Escolher…","Modelos adicionais…","Cancelar","EDITAR LEGENDAS","Pronto.","Legenda","Fala","Texto","Reproduzir legenda","Reproduzir fala","Reproduzir nova posição","Reproduzir","Pausa","Ir para:","Ir para o tempo","Copiar tempo atual","Seguir reprodução","Início:","Fim:","Tolerância:","Rigorosa","Padrão","Flexível","Personalizada","APLICAR (Ctrl+Enter)","QUEBRAR LINHAS","DIVIDIR","DIVISÃO INTELIGENTE","UNIR À SEGUINTE","ELIMINAR LINHA","Transferir","Remover","Não instalado","Deteção automática","NÃO ENCONTRADO","FIÁVEL","VERIFICAR","FRACO"],
"ru": ["Справка","Файл","Быстрый старт","Горячие клавиши (F1)","Руководство (PDF)","Руководство (текст)","Что нового","Поддержать разработку…","О программе","Язык программы","Язык:","Модель:","Выбрать…","Дополнительные модели…","Отмена","РЕДАКТИРОВАТЬ СУБТИТРЫ","Готово.","Субтитр","Речь","Текст","Воспроизвести субтитр","Воспроизвести речь","Воспроизвести новую позицию","Воспроизвести","Пауза","Перейти к:","Перейти ко времени","Копировать текущее время","Следовать за воспроизведением","Начало:","Конец:","Допуск:","Строгий","Стандартный","Свободный","Пользовательский","ПРИМЕНИТЬ (Ctrl+Enter)","ПЕРЕНОС СТРОК","РАЗДЕЛИТЬ","УМНОЕ РАЗДЕЛЕНИЕ","ОБЪЕДИНИТЬ СО СЛЕДУЮЩИМ","УДАЛИТЬ СТРОКУ","Скачать","Удалить","Не установлено","Автоопределение","НЕ НАЙДЕНО","НАДЁЖНО","ПРОВЕРИТЬ","СЛАБО"],
"zh": ["帮助","文件","快速开始","键盘快捷键 (F1)","用户指南 (PDF)","用户指南（文本）","新增功能","支持开发…","关于","程序语言","语言：","模型：","选择…","其他模型…","取消","编辑字幕","就绪。","字幕","语音","文本","播放字幕","播放语音","播放新位置","播放","暂停","转到：","转到时间","复制当前时间","跟随播放","开始：","结束：","容差：","严格","标准","宽松","自定义","应用 (Ctrl+Enter)","换行","拆分","智能拆分","与下一条合并","删除行","下载","移除","未安装","自动检测","未找到","可靠","检查","较弱"],
"ja": ["ヘルプ","ファイル","クイックスタート","キーボードショートカット (F1)","ユーザーガイド (PDF)","ユーザーガイド（テキスト）","新機能","開発を支援…","バージョン情報","プログラムの言語","言語:","モデル:","選択…","追加モデル…","キャンセル","字幕を編集","準備完了。","字幕","音声","テキスト","字幕を再生","音声を再生","新しい位置を再生","再生","一時停止","移動先:","時刻へ移動","現在時刻をコピー","再生を追跡","開始:","終了:","許容範囲:","厳密","標準","緩やか","カスタム","適用 (Ctrl+Enter)","行を折り返す","分割","スマート分割","次と結合","行を削除","ダウンロード","削除","未インストール","自動検出","見つかりません","信頼","要確認","低精度"],
"ko": ["도움말","파일","빠른 시작","키보드 단축키 (F1)","사용자 안내서 (PDF)","사용자 안내서 (텍스트)","새로운 기능","개발 지원…","정보","프로그램 언어","언어:","모델:","선택…","추가 모델…","취소","자막 편집","준비됨.","자막","음성","텍스트","자막 재생","음성 재생","새 위치 재생","재생","일시 정지","이동:","시간으로 이동","현재 시간 복사","재생 위치 따라가기","시작:","끝:","허용 범위:","엄격","표준","완화","사용자 지정","적용 (Ctrl+Enter)","줄 바꿈","분할","스마트 분할","다음 항목과 병합","행 삭제","다운로드","제거","설치되지 않음","자동 감지","찾을 수 없음","신뢰","검토","낮음"],
"ar": ["مساعدة","ملف","بدء سريع","اختصارات لوحة المفاتيح (F1)","دليل المستخدم (PDF)","دليل المستخدم (نص)","ما الجديد","دعم التطوير…","حول","لغة البرنامج","اللغة:","النموذج:","اختيار…","نماذج إضافية…","إلغاء","تحرير الترجمة","جاهز.","الترجمة","الكلام","النص","تشغيل الترجمة","تشغيل الكلام","تشغيل الموضع الجديد","تشغيل","إيقاف مؤقت","انتقال إلى:","انتقال إلى الوقت","نسخ الوقت الحالي","متابعة التشغيل","البداية:","النهاية:","التفاوت:","صارم","قياسي","مرن","مخصص","تطبيق (Ctrl+Enter)","التفاف السطور","تقسيم","تقسيم ذكي","دمج مع التالي","حذف الصف","تنزيل","إزالة","غير مثبت","اكتشاف تلقائي","غير موجود","موثوق","مراجعة","ضعيف"],
"tr": ["Yardım","Dosya","Hızlı başlangıç","Klavye kısayolları (F1)","Kullanıcı kılavuzu (PDF)","Kullanıcı kılavuzu (metin)","Yenilikler","Geliştirmeyi destekle…","Hakkında","Program dili","Dil:","Model:","Seç…","Ek modeller…","İptal","ALTYAZILARI DÜZENLE","Hazır.","Altyazı","Konuşma","Metin","Altyazıyı oynat","Konuşmayı oynat","Yeni konumu oynat","Oynat","Duraklat","Git:","Zamana git","Geçerli zamanı kopyala","Oynatmayı takip et","Başlangıç:","Bitiş:","Tolerans:","Sıkı","Standart","Esnek","Özel","UYGULA (Ctrl+Enter)","SATIRLARI KAYDIR","BÖL","AKILLI BÖL","SONRAKİYLE BİRLEŞTİR","SATIRI SİL","İndir","Kaldır","Yüklü değil","Otomatik algılama","BULUNAMADI","GÜVENİLİR","KONTROL","ZAYIF"],
"pl": ["Pomoc","Plik","Szybki start","Skróty klawiaturowe (F1)","Podręcznik użytkownika (PDF)","Podręcznik użytkownika (tekst)","Co nowego","Wesprzyj rozwój…","O programie","Język programu","Język:","Model:","Wybierz…","Dodatkowe modele…","Anuluj","EDYTUJ NAPISY","Gotowe.","Napis","Mowa","Tekst","Odtwórz napis","Odtwórz mowę","Odtwórz nową pozycję","Odtwórz","Pauza","Przejdź do:","Przejdź do czasu","Kopiuj bieżący czas","Śledź odtwarzanie","Początek:","Koniec:","Tolerancja:","Ścisła","Standardowa","Luźna","Niestandardowa","ZASTOSUJ (Ctrl+Enter)","ZAWIJAJ WIERSZE","PODZIEL","INTELIGENTNY PODZIAŁ","POŁĄCZ Z NASTĘPNYM","USUŃ WIERSZ","Pobierz","Usuń","Nie zainstalowano","Automatyczne wykrywanie","NIE ZNALEZIONO","PEWNE","SPRAWDŹ","SŁABE"]
}

for code, values in packs.items():
    if len(values) != len(keys):
        raise SystemExit(f"{code}: {len(values)} translations, expected {len(keys)}")
    data = dict(base)
    data.update(dict(zip(keys, values)))
    (root / "languages" / f"{code}.json").write_text(
        json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
